server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /products {
        proxy_pass http://backend:8081/products;
    }

    location /categories {
        proxy_pass http://backend:8081/categories;
    }

    location /orders {
        proxy_pass http://backend:8081/orders;
    }

    location /auth/whoami {
        proxy_pass http://backend:8081/auth/whoami;
    }
    
}
