upstream backend {
    server backend:8081;
    server backend:8082;
}
server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /products {
        proxy_pass http://backend/products;
    }

    location /categories {
        proxy_pass http://backend/categories;   
    }

    location /orders {
        proxy_pass http://backend/orders;   
    }

    location /auth/whoami {
        proxy_pass http://backend/auth/whoami;   
    }
    
}
