version: '3'

services:
    backend:
        build: ./backend
        ports:
            - 8081:8081
        volumes:
            - backendVolume:/app
        networks:
            - app

    frontend:
        build: ./frontend
        ports: 
            - 9990:8080
        networks:
            - app
        volumes:
            - frontendVolume:/usr
        depends_on:
            - backend
networks:
    app:
        driver: bridge

volumes:
    backendVolume:
    frontendVolume: